### ISSUE TITLE
jscs line breaks

### ISSUE THREAD

**Issue by TrySound** [meandmax/lory#10]
`"validateLineBreaks": "LF"` doesn't allow to validate code on windows. So, I suggest you to remove it, because git will automatically replace linebreaks.

**Comment by meandmax** [comment]
Have you tried this:

https://github.com/karma-runner/karma/issues/993

or 

https://github.com/ramda/ramda/issues/468

cheers Max

**Comment by TrySound** [comment]
Thanks, will try.
