### ISSUE TITLE
Removing the default export breaks the public API without a major update

### ISSUE THREAD

**Issue by ZauberNerd** [meandmax/lory#100]
The change in 95aa9d4 is a breaking change but does not increase the major version of this package.
see: https://github.com/meandmax/lory/commit/95aa9d4e878baa4f400581138e98581e381975bd#commitcomment-14328452

**Comment by TrySound** [comment]
:+1:

**Comment by KingHenne** [comment]
+1

**Comment by meandmax** [comment]
ptal @ZauberNerd @TrySound @KingHenne 

https://github.com/meandmax/lory/tree/revert-babel6

I have not thought about that this is actually a breaking change, sorry ;-) ...

For the reason that Babel6 is currently a big mess I made a step back to good old Babel5 and also pinned down all other dependencies to their fixed versions.

Have a nice weekend!
Max

**Comment by TrySound** [comment]
@meandmax What's wrong with babel6?

**Comment by meandmax** [comment]
@TrySound I will wait until the Babel6 fixing flood is over. At least I need a solution that will not break the UMD wrapper and will work as a default in all common js environments.

**Comment by TrySound** [comment]
@meandmax Try [rollup](https://github.com/rollup/rollup). Much smaller then webpack loader. Supports any output format

**Comment by meandmax** [comment]
As I discussed with @ZauberNerd and a couple of other lory users, we will keep the changes with Babel6 and for the future I will be more careful with breaking changes.

Have a nice weekend!
Max
