### ISSUE TITLE
feature request: centerMode option (ref: slick)

### ISSUE THREAD

**Issue by kubosho** [meandmax/lory#11]
Hello.

I currently working replace carousel library from [slick](http://kenwheeler.github.io/slick/) to lory.

This work want to centerMode option of slick, but lory is not implement centerMode option.

Are you planning to do it in the future?

Thanks.

**Comment by meandmax** [comment]
Hey @kubosho,

thought about that feature a couple of times and was just waiting if someone really needs it. So I will implement it, because I think as well that this is a basic option.

cheers Max

**Comment by kubosho** [comment]
Thanks to reply @meandmax. I looking forward to implementing centerMode option.

**Comment by kubosho** [comment]
Hi, @meandmax.

I trying to implement centerMode now, because my current work needed immediately centerMode option.

If implement centerMode completed, I will sent Pull Request.

Thanks.

**Comment by meandmax** [comment]
Hey @kubosho,

yeah! I really appreciate that! Just back from Portugal and already lots of work to do! If you need help, just ask, I would implement the feature at the weekend if you have not started yet!

cheers Max

**Comment by kubosho** [comment]
@meandmax 
I implement centerMode complete. I'm going to send Pull Request soon.
