### ISSUE TITLE
Support of direct slide switching (w/o animation effects)

### ISSUE THREAD

**Issue by ginsterbusch** [meandmax/lory#125]
Thanks to the fact that you've effectively eleminated any kind of way to directly get in contact you, I am forced to ask my rather simple question in here:

Does the slideshow script support DIRECT jumps to a specific slide? That is, __without__ doing any kind of animation effect, basically switching directly to the selected slide? 

TIA,
cu, w0lf.

**Comment by meandmax** [comment]
Hey ginsterbusch:

in the optionsobject set the slideSpeed to 0, that should work.

lory(sliderElement, {slideSpeed: 0});

**Comment by ginsterbusch** [comment]
Guess I wasnt specific enough: How would I do that when the object is already instantiated? 
The use case is rather simple: You've got a bunch of images, and on click you get an overlay, that displays the image plus HTML content (eg. caption or a bigger descriptional text block).

Think of it in terms of a fancy, responsive lightbox thingy.

So when the user closes that overlay, and then goes on to click on a totally different image, you'd normally get the (unwanted) effect of the overlay opening and the slideshow still spinning. And that is what my question is actually about: Is it possible to instantly switch to a specific slide AFTER script initialization?

That basically would mean changing options on the fly (which is what an API is supposed to do or help to achieve).

cu, w0lf.

**Comment by Yimiprod** [comment]
I know it has been closed but wan't an anwser too.
Since the options are extended, we can't do trick like change the option.slideSpeed to 0 then revert it back to normal speed.

**Comment by ginsterbusch** [comment]
@Yimiprod well, it's pretty simple: I'm rolling my own (framework-agnostic, API-exposing, etc. slideshow script), as there aint not slideshow / carousel scripts around, that offer this much flexibility ;)

cu, w0lf.
