### ISSUE TITLE
Add dot pager

### ISSUE THREAD

**Issue by TrySound** [meandmax/lory#13]
Simple pager like [here](http://jquery.malsup.com/cycle2/demo/pager.php)

**Comment by meandmax** [comment]
Hey @TrySound,

Would be interesting if you could implement your on pager module and using the hooks and the public api from lory for the state updates. What do you think about that?

I think that would be the right way for these kind of features, what do you think about that?

cheers Max

**Comment by TrySound** [comment]
@meandmax  What is hooks?

**Comment by TrySound** [comment]
@meandmax  I think you need to move functions outside of lory constructor for optimization.

**Comment by meandmax** [comment]
Hey @TrySound,

could you explain what you mean? You have some default callback functions (hooks) where you can set what should be executed e.g. before slide -> there you could register a callback of your dotPager that before or after slide the dotPager should be executed. 

Look into the defaultOptions object.

Then we need to add a function to get the current index and we need a function to actually count how many slides the slider have.

I think with these additional functions you would be able to build the dotPager, what do you think? What I really try to prevent is to integrate all features into lory! There has to be a way to keep the slider as lean as possible while it is still extendable.

What´s your thoughts about that?

cheers Max

**Comment by meandmax** [comment]
Hey @TrySound,

I added the function returnIndex to the public api. If I would add the callback "afterSlide" to the options would that allow implementing a dotpager independent of lory?

cheers Max

**Comment by TrySound** [comment]
@meandmax How to init pager for every instance calling just API?
In martin I realized hooks as a function calling before init callback.

**Comment by shshaw** [comment]
Would also need to consider how the paging would function with the `slidesToScroll` option. Should the number of dots correspond to the total number of slides, or to the number of 'pages' (`total / slidesToScroll`)? I'd expect the latter.

**Comment by davidchase** [comment]
I was able to create a pager, that works with multiple instances of lory on a page..
**+1** for keeping the slider simple and providing hooks and `returnIndex` @meandmax

**Comment by meandmax** [comment]
Oh nice! Do you think you could put it on Github that everybody can see how you made it?

thanks @davidchase

**Comment by nstanard** [comment]
How to make a dot pager with Lory.js

http://codepen.io/nstanard/pen/jrwymd
http://codepen.io/nstanard/pen/EgvVpV
