### ISSUE TITLE
error with 1.6.8 `TypeError: _lory2.default is not a function`

### ISSUE THREAD

**Issue by lalop** [meandmax/lory#148]
use lory in a webpack build and I get this error when I call `lory(slider, {});`
My code is only what is writen in the Readme.

It seems that _lory2 is due to webpack but I can't say more.

**Comment by lalop** [comment]
the error come from the `import`

**Comment by lalop** [comment]
I'm not sure if it's the readme that needs to be updated or the export;

**Comment by meandmax** [comment]
Hey @lalop 

I will look into this! Thanks for the report!

Max

**Comment by meandmax** [comment]
Babel 6 changes how it exports the default and the reason for this is actually valid es6. Everything before was incorrect behavior. So the solution here is to update the README (which I will do immediatly) and import lory as you already suggested.

Here the discussion: http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

So for es5/commonjs it will be: 
```js
var lory =  require('lory.js').lory
```
And for es6 it will be:

```js
import {lory} from 'lory.js';
```

Any suggestions?

Max

**Comment by meandmax** [comment]
Have a look:

https://github.com/meandmax/lory/pull/150
