### ISSUE TITLE
Tests in IE failing on Travis CI

### ISSUE THREAD

**Issue by meandmax** [meandmax/lory#149]
Does anybody has an idea why the tests in IE are failing? I really do not have any idea ...

Thanks for help!

![bildschirmfoto 2015-12-11 um 10 26 14](https://cloud.githubusercontent.com/assets/6309638/11806368/d7d63dcc-a312-11e5-9021-07d74857758b.png)

**Comment by tshedor** [comment]
@meandmax IE 9 doesn't support [`classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList). [This polyfill](https://github.com/eligrey/classList.js/) did the trick.

**Comment by tshedor** [comment]
Depending on how much you value IE9 support, you could replace [the problem lines](https://github.com/meandmax/lory/blob/master/dist/lory.js#L124) with [`classList`-less functions](http://jaketrent.com/post/addremove-classes-raw-javascript/). 

I've got some experience with this and can open a PR if that'd be easier.

**Comment by meandmax** [comment]
Hey @tshedor,

thanks for the help!

As you can see in "saucelabs.karma.conf.js" I already integrated this polyfill for the tests, and it worked so before I implemented async tests which actually measure the current offset of the slider or am I doing anything wrong?

```
   files: [
            'dist/lory.js',
            'test/lory.test.js',
            'demo/app.css',
            'http://cdnjs.cloudflare.com/ajax/libs/classlist/2014.01.31/classList.min.js',

            {
                pattern: 'test/*.html'
            }
        ],
```

Thanks a lot for investing some time!
Max

**Comment by meandmax** [comment]
And actually there are just 7 tests which fail in the IE9, the rest works so far. If there would be a problem with classlist, then all tests in IE9 would fail or what do you think?

Max

**Comment by tshedor** [comment]
Yeah, that's a good point - they would all fail if it was classList. I'll try this in a VM.

**Comment by tshedor** [comment]
All seven of those tests include the `waitForTransitionEnd` callback - I wonder if it's having a hard time with the `&&` in `done && done()`?

**Comment by meandmax** [comment]
I will give it a shot!

**Comment by meandmax** [comment]
https://github.com/meandmax/lory/pull/153

deactivated the tests in IE9 temp. ... if anybody has an idea, feel free!

Max
