### ISSUE TITLE
Initialising multiple sliders only initialises prev/next buttons for first slider.

### ISSUE THREAD

**Issue by wjonesy** [meandmax/lory#190]
I am using custom classes for classNameFrame and classNameSlideContainer, the first slider is fine.

All the other sliders work, but the prev/next buttons only work on the first slider.

`(function () {
    var School = {
        init: function () {
            this.sliders = document.querySelectorAll('.js-school-tabs-slider-wrapper');
            this.bindEvents();
        },
        bindEvents: function () {
            document.addEventListener('DOMContentLoaded', this.initSlider);
        },
        initSlider: function () {
            if (School.sliders != null) {
                Array.prototype.slice.call(School.sliders).forEach(function (element, index) {
                   lory(element, {
                        classNameFrame: 'js-school-tabs-slider-frame',
                        classNameSlideContainer: 'js-school-tabs-slide-container',
                        infinite: 1,
                        enableMouseEvents: true
                    });                     
                });

            }
        },
    }
    School.init();
})();`

HTML - more than one of these divs on the page

`<div class="js-school-tabs-slider-wrapper">
                                        
                                        <div class="school-tabs-slider-frame js-school-tabs-slider-frame">
                                            <div class="js-school-tabs-slide-container school-tabs-slide-container">

                                                <div class="school-tabs-slider-item js-school-tabs-slider-item">
                                                    <div class="row">
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1"> tab 2CLASS 2</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>

                                                    </div>
                                                    <div class="row">
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS2</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                    </div>

                                                </div>
                                                <div class="school-tabs-slider-item js-school-tabs-slider-item">
                                                    <div class="row">
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1"> tab 2CLASS 2</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>

                                                    </div>
                                                    <div class="row">
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS 2</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                        <div class="col-xs-5ths">
                                                            <div class="js-school-class-list-item school-class-list-item" data-class="1">CLASS</div>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        <button type="button" class="js-school-tabs-slider-prev js_prev"><</button>
                                        <button type="button" class="js-school-tabs-slider-next js_next">></button>
                                    </div>`

**Comment by meandmax** [comment]
There is a typo in in the following lines:

```
 <button type="button" class="js-school-tabs-slider-prev js_prev"><</button>
 <button type="button" class="js-school-tabs-slider-next js_next">></button>
```
should be this:

```
 <button type="button" class="js-school-tabs-slider-prev js_prev"></button>
 <button type="button" class="js-school-tabs-slider-next js_next"></button>
```

I query the buttons based on the outer `js_slider` so it normally should work.

https://github.com/meandmax/lory/blob/master/src/lory.js#L227-L228

If u still have problems, send me your source and I will have a look.

cheers Max
