### ISSUE TITLE
Supported browsers

### ISSUE THREAD

**Issue by TrySound** [meandmax/lory#20]
IE9 also supported but with graceful degradation. Everything works fine.

**Comment by meandmax** [comment]
I don`t have IE9 in the current browser matrix ... does it work? :)

cheers Max

**Comment by TrySound** [comment]
@meandmax Yes, I tried it on my virtual machine. It works fine without transitions.

**Comment by shshaw** [comment]
I just tested it on IE9 as well and the demos seem to be working as expected, minus transitions. :+1:

**Comment by meandmax** [comment]
Thanks for reporting it. I added IE9 to supported Browsers.

Have a nice week
cheers Max
