### ISSUE TITLE
Could you update babel build?

### ISSUE THREAD

**Issue by Jinkwon** [meandmax/lory#245]
Hi, lory.

I have some issue with lory.js.
In lory babel builder version,  default is reserved keyword in IE8.
So it takes break with load lory, even it does not use it.
Babel 6.7.4 version fixed this issue with es3 plugin.
Could you review this issue?

```javascript
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
default should be ['default']

Follow this release version.
https://github.com/babel/babel/releases/tag/v6.7.4

**Comment by meandmax** [comment]
Updated all dependencies! Please tell me if everything works fine now!
