### ISSUE TITLE
Collaboration 

### ISSUE THREAD

**Issue by afmarchetti** [meandmax/lory#250]
Hi Meandmax, you are a genius! lory is awesome.
I'm Andrea a Developer from Italy :-)

Can i use lory in my new front-end framework? take a look: https://github.com/afmarchetti/alux
It would be great to add a slider as lory, obviously with the credits and the license you want.

Thank you for your great job,
have a nice day.
Andrea.

**Comment by meandmax** [comment]
As I said! Of course you can :+1: its open source ;)
