### ISSUE TITLE
[Help] Slide width 100%

### ISSUE THREAD

**Issue by DCKT** [meandmax/lory#255]
Hi,

I'm encountering a strange issue, I put all the div to `width: 100%;` but when I look in the Dev tools, it's not work and by the way the translate doesn't work well.

Here is a screen of : 
<img width="426" alt="capture d ecran 2016-04-11 a 20 08 05" src="https://cloud.githubusercontent.com/assets/1548421/14437427/6cde2e0a-0021-11e6-9358-cb73bc09bdf6.png">

The `.frame` div fill correctly the container

Do you have an idea about this ? 

Thanks for your great works !

**Comment by nstanard** [comment]
Please isolate the issue. ^^

codepen.io

**Comment by nstanard** [comment]
@DCKT Please provide a link to a demo on codepen.io so we can take a look at what issue you are having.

**Comment by acenkus** [comment]
To make lory full screen I just wrote this hack... But maybe we can add option to 100% width by parent container?
`var lory_slides_width = function(e) {
		var lory_slide = document.querySelectorAll('.js_slide'),
		w = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;

		for (var i = 0; i < lory_slide.length; i++) {
			lory_slide[i].style.width = w + 'px';
		}

	 };`

**Comment by nstanard** [comment]
I'm a little confused why a hack is needed to make the carousel full width. 

http://www.lovelyskin.com/skin-specialists-omaha 

The site above has lory setup although there is only a single slide so it doesn't actually function at the moment. But it is full width and I promise it's lory.js setup.

**Comment by nstanard** [comment]
Please re-open with an example if you are having issues with this still.

**Comment by veganista** [comment]
I'm having a bit of trouble with 100% width slides.

It keeps snapping back on release.

I've put together a fiddle here: https://jsfiddle.net/eaoobsw3/1/

**Comment by peterrattew** [comment]
The second fiddle is still broke for me and shows a part of the second slide but if you set padding to 0 on `.slides` then it works fine.
