### ISSUE TITLE
does not activate the last element and incorrect positioned

### ISSUE THREAD

**Issue by slavikse** [meandmax/lory#257]
<a href="http://www.zimagez.com/zimage/screenshot-14042016-173634.php">
  <img src="http://www.zimagez.com/miniature/screenshot-14042016-173634.php" />
</a>
on the screen: this is the last slide
as you can see he is not selected as active and not being correctly positioned.

code:

```
  .slider.js_multislides.multislides
    .frame.js_frame
      ul.slides.js_slides
        li.js_slide: img(src='image/projects_1.jpg' width='226' height='164' alt='1')
        li.js_slide: img(src='image/projects_2.jpg' width='226' height='164' alt='2')
        li.js_slide: img(src='image/projects_3.jpg' width='226' height='164' alt='3')
        li.js_slide: img(src='image/projects_4.jpg' width='226' height='164' alt='4')
        li.js_slide: img(src='image/projects_1.jpg' width='226' height='164' alt='1')
        li.js_slide: img(src='image/projects_2.jpg' width='226' height='164' alt='2')
        li.js_slide: img(src='image/projects_3.jpg' width='226' height='164' alt='3')
        li.js_slide: img(src='image/projects_4.jpg' width='226' height='164' alt='4')
        li.js_slide: img(src='image/projects_1.jpg' width='226' height='164' alt='1')
        li.js_slide: img(src='image/projects_2.jpg' width='226' height='164' alt='2')
    span.js_prev.prev.icon-projects_arrow
    span.js_next.next.icon-projects_arrow
```

```
.slider
  position relative
  margin 0 auto
  width 226px

  .frame
    margin 0 auto
    width 226px
    overflow hidden
    white-space nowrap

  .slides 
    margin 0
    padding 0
    display inline-block

  li 
    position relative
    display inline-block
```

ps: in the rest of the library is great! Thank you for your trouble! :)

**Comment by anghi** [comment]
The missing font-size: 0; in the .frame class causes wrong calculation

**Comment by toineghi** [comment]
The missing font-size: 0; on the .frame class causes wrong calculations.

**Comment by riotcku** [comment]
Read my answer on https://github.com/meandmax/lory/issues/197

I believe your problem is related, and I have a solution up there.

**Comment by nstanard** [comment]
Hey @slavikse,

Are you able to provide a link to that example?

**Comment by gmenih341** [comment]
Had the same problem. My issue was that I didn't add `DOMContentLoaded` listener, and init `lory` in there. After doing that, it was properly positioned.

**Comment by nstanard** [comment]
@slavikse If you can provide a link to a demo with a reproducible issue please open a new issue. I do believe font size 0 missing is what would cause this.

**Comment by slavikse** [comment]
@nstanard that was a long time ago. I suspect it was a newline (enter) between inline elements.
