### ISSUE TITLE
Calculs size calcul slide break if loading the lib too quickly

### ISSUE THREAD

**Issue by Yimiprod** [meandmax/lory#266]
If we append the slider in the dom and load a lory.js slider, the calcul can be wrong, because the dom haven't already registered the width of the slides.
It can be restored with a call to `.reset()` the first time a slide animation is triggered, for exemple.
That way the calcul is done when the user send the first slide.

**Comment by meandmax** [comment]
initialize lory when the DOM is fully loaded, then this shouldn't be a problem, right?

cheers Max
