### ISSUE TITLE
Option to change default CSS class name

### ISSUE THREAD

**Issue by caiotarifa** [meandmax/lory#29]
What about extend options to change the default CSS class name?

```
var frame = slider.querySelector('.js_frame');
var slideContainer = frame.querySelector('.js_slides');
var prevCtrl = slider.querySelector('.js_prev');
var nextCtrl = slider.querySelector('.js_next');
```

**Comment by meandmax** [comment]
Could you give me some arguments why do you need these dynamic class names?

cheers Max

**Comment by Cordazar** [comment]
One thing could be if you wanted to keep a bem-style naming scheme and not use extra js-classes for the slideshow.

**Comment by caiotarifa** [comment]
As the @Cordazar said, I wouldn't want follow the pattern that the plugin requires me.

I believe this is an easy feature to implement and don't encumber in loss performance or increased file size.

So, what about? :)
