### ISSUE TITLE
iPhone starts on second slide

### ISSUE THREAD

**Issue by jtree5757** [meandmax/lory#299]
Just as the title says. Has anyone else come across this?

**Comment by meandmax** [comment]
Do u still have this problem, seems nobody else had this? If so, please give a bit more description and details/screenshots ..

**Comment by nstanard** [comment]
Yea I have multiple iOS devices but have not seen this issue. I have noticed a rewind issue as I mentioned in #318. What device are you using specifically @jtree5757? Also, can you screen record the issue?

**Comment by nstanard** [comment]
Please open another issue with a demo and more information on your device if you find this is still an issue.
