### ISSUE TITLE
Swipe on iphone bit janky

### ISSUE THREAD

**Issue by davidchase** [meandmax/lory#30]
So if you visit the [lory website](http://meandmax.github.io/lory/) on the iphone.. i used chrome and try to swipe say `single element fixed with [infinite]` it seems a bit janky going from slide to slide...

On the contrary if you use the arrow keys the slides seem to move smoothly as expected.

Anyone else have a similar issue?

Also tested on safari a bit better but also not as smooth as using the arrow keys...

cheers

**Comment by icetee** [comment]
+1

**Comment by Cordazar** [comment]
I'm looking into this a bit more. If I find something I'll make a PR.

**Comment by Cordazar** [comment]
@davidchase Could you please try this with the current demo page and see if PR #37 helped?

**Comment by davidchase** [comment]
@Cordazar i loaded it up in my chrome browser on my iphone in incognito tab and same as before.. the swipe behavior isn't on par with the arrow keys on either side of the slider..

So when you swipe the demo slides they jump/snap to the next or previous, however if you use the arrows the transitions are smooth like expected

**Comment by meandmax** [comment]
@davidchase, still an issue after merging this: https://github.com/meandmax/lory/pull/336

Please check ... :)

**Comment by davidchase** [comment]
@meandmax checked it out on google chrome and safari looks great 👍
