### ISSUE TITLE
iOS touch to scroll on the slider

### ISSUE THREAD

**Issue by nstanard** [meandmax/lory#318]
I've only tried this on my iPhone 5 and this old iPad. But... Touching the slider to scroll down causes the image to jump to the first slide. It corrects itself after the next transition. 

On my iPhone this happens every time. On this iPad I have to be rather aggressive with the touch/scroll interaction to get it to happen. I loaded the lory.js demo site and confirmed it happens to me on there too using my iPhone. If I get a chance I will look into this myself. But at least wanted to mention it.

**Comment by nstanard** [comment]
Note: the rewind option causes the jump to the first slide to actually animate.

**Comment by meandmax** [comment]
Hey @nstanard 

After merging this: https://github.com/meandmax/lory/pull/312 + if u set your rewind to false that should not happen anymore, right?

Cheers Max

**Comment by nstanard** [comment]
@meandmax What events should cause the slider to rewind? I know resize causes it to rewind if that option is not set to false. However, on my iPhone 5 simply scrolling down the page causes the rewind to happen.

**Comment by nstanard** [comment]
@meandmax Okay I understand why this is happening now. My iPhone 5 is firing a resize event because of the URL bar that hides and shows on scroll up and down. I guess I'll just have to set all my sliders to rewind false. 👍

**Comment by nstanard** [comment]
@meandmax Okay I understand why this is happening now. My iPhone 5 is firing a resize event because of the URL bar that hides and shows on scroll up and down. I guess I'll just have to set all my sliders to rewind false. 👍
