### ISSUE TITLE
Breakpoint options

### ISSUE THREAD

**Issue by linnett** [meandmax/lory#327]
Like in slick slider, you can change the options at certain breakpoints. I'm just wondering if this functionality is available for this plugin and how I would go about implementing it. Thanks

**Comment by meandmax** [comment]
Is not available for lory, lory is a lot lighter than slick. So if you nedd a lot more configuration, lory is probably not the right slider for this.

cheers Max

**Comment by JanssenRodrigues** [comment]
Still not possible?
