### ISSUE TITLE
jquery plugin without $

### ISSUE THREAD

**Issue by dbeja** [meandmax/lory#353]
Hi,

I think the jQuery plugin is not correct, because if I use it on a Wordpress theme where the $ is not defined (to avoid conflicts), your plugin is waiting for the $ and it fails:

`jquery.lory.js?ver=4.4.4:65 Uncaught TypeError: Cannot read property 'fn' of undefined`

I think it should have an anonymous function with the object jQuery and inside you could use the $.

**Comment by meandmax** [comment]
You still need a way to inject jQuery, right?
