### ISSUE TITLE
slideTo causes issue with scrolling when target slide is not visible

### ISSUE THREAD

**Issue by rtyshyk** [meandmax/lory#405]
Hello @meandmax,

It is impossible for a user to use manual scroll (dragging or arrows) after slideTo to a slide which is beyond the frame.
See example: http://codepen.io/rtyshyk/pen/KgdKqY/

Do you have any solution?

Thanks,
Roman

**Comment by Cordazar** [comment]
That example works in my Firefox 50.

**Comment by rtyshyk** [comment]
@Cordazar, it is reproducible on latest versions of google chrome (53.0.2785.101 m (64-bit)) and firefox (48.0.2)
see screencast  http://screencast.com/t/Kp34ABDd

**Comment by nstanard** [comment]
@rtyshyk 

https://codepen.io/anon/pen/WOddPy

I do not see any issues with the slider in the link above. In the link you provided (currently) you're using `slidesToScroll: 1` with 4 visible slides. That is not the intended use of the slider features.
