### ISSUE TITLE
ES6, modularize + webpack

### ISSUE THREAD

**Issue by meandmax** [meandmax/lory#41]
@TrySound, @Cordazar 

I think about reorganizing the code in modules with es6 features and bundle everything up with webpack and babel?

What`s your thoughts on that?

Here some changes, what it could look like?
https://github.com/meandmax/lory/tree/feature/webpack

cheers Max

**Comment by TrySound** [comment]
@meandmax es6 looks good. I don't use webpack.

**Comment by Cordazar** [comment]
I'm all for ES6 and babel. Haven't used webpack though so I can't say either way, modules I do like though.

**Comment by TrySound** [comment]
Gulp forever :)))

**Comment by meandmax** [comment]
The only problem that I see with es6, babel and modules is that it gets more than a kb bigger in the minified version. Reason for that is the boilerplate code from babel +  webpack. 

@TrySound: I do like Gulp but with lory I don`t think Gulp makes a heavy difference, so I would rather stay with grunt until all other issues or problems are solved ... :D

Still thinking about it ...

Have a good week! Max

**Comment by meandmax** [comment]
Any suggestions on my latest changes?

https://github.com/meandmax/lory/tree/feature/es6/

cheers Max
