### ISSUE TITLE
Tag 2.2.0: Wrong version in bower.json and no changes in dist?

### ISSUE THREAD

**Issue by benni3005** [meandmax/lory#413]
Hi there,

first of all thanks for releasing this awesome slider. It's exactly what I'm needing at the moment. But there are two problems I encountered today while using it.

1. The version declared in the `bower.json` still states 1.2.6, so Bower was bugging me about it. It can handle those things automatically and installed 2.2.0, but there was a notice about a version mismatch: 
> bower lory#*                  mismatch Version declared in the json (1.2.6) is different than the resolved one (2.2.0)

2. The tag now has the option `rewindOnResize`, but only in the `src` directory. The `dist` directory was not updated and so it's not usable when using it from there.

You would make me absolutely happy if you could solve these two little things :)

Thanks in advance,
Benni

**Comment by meandmax** [comment]
I already updated the version of bower to the current one. The current dist files are up to date and with rewindOnResize like here: 

https://github.com/meandmax/lory/blob/master/dist/lory.js#L370

Maybe Bower is doing something strange. As I updated the bower version a couple of days ago could you re-install lory and see if there are still old distribution files?

Thanks Max

**Comment by benni3005** [comment]
In the meantime I saw, that you did that in the master branch. But the tag was created before you did that, so https://github.com/meandmax/lory/blob/v2.2.0/dist/lory.js does not contain the `rewindOnResize` option. I think you just have to release a 2.2.1, so Bower can recognize the update.

Benni

**Comment by meandmax** [comment]
I think this is fixed now ;)!

**Comment by benni3005** [comment]
It does. Thank you 👍
