### ISSUE TITLE
Next and Prev buttons

### ISSUE THREAD

**Issue by dhakelila** [meandmax/lory#445]
Hi there! 

First, congratulations for your nice plugin! 

Second, I have spent some time trying to figure out where the arrows for prev and next slider were. Not a big deal, I love to be able to put the arrows where I need them but I think that would be VERY useful if you add that info into the first specification you have: PREREQUISITED HTML STRUCTURE.

Thank you!

**Comment by nstanard** [comment]
I don't feel this is really _needed_ but... Next time you want something like that you can pull the project down and add it, then open a PR. ;)

https://github.com/meandmax/lory/pull/447
