### ISSUE TITLE
[suggestions] React component

### ISSUE THREAD

**Issue by sabeurthabti** [meandmax/lory#48]
This would be a nice, React component.

**Comment by meandmax** [comment]
Hello @sabeurthabti,

in my opinion is this not the purpose of lory and I already thought about this quite a lot. I think to translate lory in react, you actually have to write lory from the scratch new. lory is for the use cases where you not want or you can`t use react.

If you need a slider which works actually with react, have a look at this:
https://github.com/akiran/react-slick

Thanks anyways, cheers
Max

**Comment by miduga** [comment]
Hi there! I'm working on a wrapper here: https://github.com/miduga/react-lory

It's still a alpha, but it's usable on most cases if you want the slider to be responsive and slide one to one. 👍  Feedback is welcomed!
