### ISSUE TITLE
JQuery plugin returns the object without 'prev/next' methods

### ISSUE THREAD

**Issue by OVes** [meandmax/lory#5]
Could you, please, check if the JQuery plugin returns the correct result for 'lory' method?
Because, I get back the JQuery object only.

Thanks a lot.

**Comment by meandmax** [comment]
Hey @OVes,

I can't check if it works, because I'm not at home for the next 9 days but if there is a problem I will fix it asap.

If anybody else can help ... I would appreciate it.

Thanks
Max

**Comment by meandmax** [comment]
Hello @OVes,

sorry for the delayed feedback ... I was on holidays. So I checked your problem and for me everything is fine ... I just didn`t document it. sorry. Now I updated the documentation and the example in the demo folder.

```js
        'use strict';

        var $elements = $('.js_simple');

        $(function() {
            $elements.lory({
                infinite: 1
            });

            $elements.data().lory.slideTo(4);
            // $elements.data().lory.prev();
            // $elements.data().lory.next();
        });
```

If you have a better idea than adding the function to the jQuery data object, feel free to make a pull request.

I hope this will help you.

cheers Max
