### ISSUE TITLE
Feature Request: zepto.js support

### ISSUE THREAD

**Issue by alexv9** [meandmax/lory#518]
Hi,

lory is a brilliant slider :) as an enhancement to the jQuery version it would be great to have a zepto.js version of it.

**Comment by nstanard** [comment]
If this is a priority for you I would suggest opening a PR with your proposed changes. I'd be happy to take a look and assist getting it merged and approved. I don't imagine it's a big priority though on the list of thing s to do.

**Comment by nstanard** [comment]
Closing for now. Again, you are welcome to open a PR for this.
