### ISSUE TITLE
Can't change slides

### ISSUE THREAD

**Issue by metaloha** [meandmax/lory#544]
No matter what is clicked, or whether I use the `slideTo()` method, slide 0 is always the active slide. I can't reproduce this on the demo page, but I can't make it not do this on my own site. I believe all the markup is correct.

The `before.lory.slide` event fires, but `currentSlide` is **always** 0, and `nextSlide` is **always** undefined.

**Comment by nstanard** [comment]
This is almost for sure a setup issue. Please ping me via Gitter chat and I'll be happy to take a look.
