### ISSUE TITLE
returnIndex can return negative numbers

### ISSUE THREAD

**Issue by curtisblackwell** [meandmax/lory#569]
Using `prev()` I'm `returnIndex()` is sometimes negative.

If a carousel has 5 slides and `infinite: 3`, here's what happens:

| `returnIndex` | New `returnIndex` after using `prev()` |
| --------------:| ---------------------------------------:|
| 0 | -1 |
| -1 | -2 |
| -2 | 3 |
| 3 | 2 |
| 2 | 1 |
| 1 | 0 |

**Comment by nstanard** [comment]
@curtisblackwell If you provide an isolated example I will re-open this.
