### ISSUE TITLE
Text in Slide?

### ISSUE THREAD

**Issue by reidblomquist** [meandmax/lory#585]
So, this project looks really slick and the touch behavior is super responsive - but I'm wondering if anyone has endeavored to get text in slides? Seems like this is super dependent on not having any text in there - unless someone can point me to directions to make it work properly with text inside I may have to use another tool.

If anything springs to mind that'd be great - if its simply meant for images it might be good to call that out more clearly in the readme.

Cheers!

**Comment by nstanard** [comment]
Although the sliders are not functional due to only having one slide. I built this skin specialists website using Lory and that text is part of the slide.

http://www.lovelyskin.com/skin-specialists-omaha

**Comment by nstanard** [comment]
![image](https://cloud.githubusercontent.com/assets/4204806/23216744/b3099dba-f8dc-11e6-8092-6438b7b6c7b6.png)

**Comment by nstanard** [comment]
Closing this issue. If you need 1:1 help I'd be happy to assist.

**Comment by njrfoto** [comment]
I also need help with this...
