### ISSUE TITLE
Rewind and infinite not working as expected

### ISSUE THREAD

**Issue by andosteinmetz** [meandmax/lory#587]
I'm having an issue where if I set the option `{ infinite: true }`, advancing backward through the carousel, the slider behaves as expected, but advancing forward, I get what I would expect for the rewind behavior (it goes backwards to the first slide), and in the console I get the error:
`Uncaught TypeError: Cannot read property 'offsetLeft' of undefined`.

If I set `{ rewind: true }`, there's no difference from when neither rewind or infinite is set to true.

Maybe there is something in my setup that is causing this, but my usage thus far mirrors very closely what's given in the docs.

My CSS is taken from the docs here, and the only option I'm setting on init is `infinite: true` or `rewind: true` (one or the other).

My markup:
```
<div class="slider js_slider">
  <div class="frame js_frame">
    <ul class="slides js_slides">
        <li class="js_slide">
          <img src="example.jpg" />
        </li>
        <li class="js_slide">
          <img src="example2.jpg" />
        </li>
        <li class="js_slide">
          <img src="example3.jpg" />
        </li>
    </ul>
  </div>
  <span class="js_prev prev">
      <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 501.5 501.5"><g><path fill="#2E435A" d="M302.67 90.877l55.77 55.508L254.575 250.75 358.44 355.116l-55.77 55.506L143.56 250.75z"/></g></svg>
  </span>
  <span class="js_next next">
      <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 501.5 501.5"><g><path fill="#2E435A" d="M199.33 410.622l-55.77-55.508L247.425 250.75 143.56 146.384l55.77-55.507L358.44 250.75z"/></g></svg>
  </span>
</div>
```

Is it a bug?

**Comment by drewfranklin** [comment]
Hey @andosteinmetz,
Infinite can be set to false or number of visible slides. So I believe you would want { infinite: 1 } instead of { infinite: true }

**Comment by drewfranklin** [comment]
Although shifting this into a feature request. I was thinking about this, and trying to think of possible scenarios where you want infinite and slidesToScroll to be different values. I couldn't think of any, but maybe it was built this way for a specific use case that I am not thinking of.
If there is not a use case maybe infinite should be a boolean value and then the number of visible slides is based on slidesToScroll?

**Comment by andosteinmetz** [comment]
Thanks! That fixes my immediate issue. 
To me, it seems natural for them to be three separate values: infinite (boolean), slidesToScroll, and slidesVisible, though I haven't looked too carefully into the code to see how the 'infinite' value is being used...

**Comment by nstanard** [comment]
@andosteinmetz This slider has a few different features and in an attempt to make them work together the code needs to know how many slides are visible for the infinite feature.
