### ISSUE TITLE
global is undefined

### ISSUE THREAD

**Issue by MRokas** [meandmax/lory#594]
Using lory with webpack, whenever I try to use `lory`, it throws this:
`TypeError: global is undefined`

My webpack config:

```
const webpack = require('webpack');

module.exports = {
  entry: {
    app: './src/app.js'
  },
  output: {
    filename: './assets/js/[name].bundle.js'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      loader: 'babel-loader',
      query: { presets: [ 'es2015', 'stage-0' ] }
    }]
  }
```

And this is app.js:
```
const lory = require('lory.js').lory;
console.log(lory)
```

Error is thrown here:
```
var NativeCustomEvent = global.CustomEvent; # here

function useNative() {
	try {
		var p = new NativeCustomEvent('cat', { detail: { foo: 'bar' } });
		return 'cat' === p.type && 'bar' === p.detail.foo;
	} catch (e) {}
		return false;
	}
....
```

lory version: `2.2.1`
webpack version: `2.2.1`

**Comment by MRokas** [comment]
from what I see, this is caused by webpack, by passing wrong global value.

**Comment by Gastonite** [comment]
replacing the import with 
`import { lory } from 'imports-loader?global=>window!lory.js';`

seems to do the trick :)

**Comment by MRokas** [comment]
@Gastonite - you forgot to mention it requires `npm i -D imports-loader`;

**Comment by nstanard** [comment]
Webpack syntax issue, closing this.
