### ISSUE TITLE
Text not wrapping in slides?

### ISSUE THREAD

**Issue by lukearmstrong** [meandmax/lory#595]
When entering text into a slide, it doesn't wrap, it just continues on one line so anything beyond the width of the slide is hidden.

I noticed this was causing the issue:
```
.frame {
    white-space: nowrap;
}
```

Trying to add `white-space: normal` to either the frame, slides, or slide results in breaking the carousel.

Adding a child element inside the slide, and adding `white-space: normal` to that appears to fix the problem, until you click onto the next slide then the carousel doesn't move to the correct position.

**Comment by nstanard** [comment]
> doesn't move to the correct position.

That's the reason the frame has white-space nowrap. If you would like text to wrap you need to create your own containers inside the slide and define widths and such.

http://www.lovelyskin.com/skin-specialists-omaha

**Comment by nstanard** [comment]
Yea if you can show me a link I'm feeling confident I can get you what you want with the text wrapping and correct positioning.
