### ISSUE TITLE
Changing number of visible slide !!

### ISSUE THREAD

**Issue by sleeman** [meandmax/lory#6]
Is there a way to change how many visible slides based on screen width !! For instance  at mobile devices i don't want to 4 small slides , i only want one slide to be visible , Is there a feature where i can do this !! 

Thx

**Comment by meandmax** [comment]
Hey @sleeman,

yes you can, but not via the options of the slider. 

You can set the slider width and the witdth of each slide via CSS and adjust them with mediaqueries for your different screen sizes.

You can have a look in the app.css of the demo folder, there I think I do exactly want you want to do.

cheers Max
