### ISSUE TITLE
requesting jquery but thought it also came without

### ISSUE THREAD

**Issue by simondavies** [meandmax/lory#609]
I am using Lory as follows through NPM:

```
   npm install --save-dev lory.js
```

and then loading within a JS class as:

```js
    import {lory} from 'lory.js';
```

But when I go ahead and compile it,  I get the error:

```
 ERROR  Failed to compile with 1 errors                                                                                                 8:25:30 PM

This dependency was not found:

* jquery in ./~/lory.js/dist/lory.js

To install it, you can run: npm install --save jquery

```

Now the issue is my project I have done without the need of jquery and completely built with vanilla js etc, so I don't want to import 'query' to just run lory.js.

But I thought it was not dependent on jquery?

Correct me if I am wrong or if using the wrong file, Thanks?

**Comment by nstanard** [comment]
It does come without, I suggest taking the file and including it directly into your project. Then you can import it without concern. But I will try to recreate this scenario soon.
