### ISSUE TITLE
Add 'initialIndex' option

### ISSUE THREAD

**Issue by tvler** [meandmax/lory#628]
It would be useful to initialize a lory slider with an initial index value, instead of just '0'.

ex:
``` js
lory(sliderElement, {
   initialIndex: 2
});
```

**Comment by tvler** [comment]
This could be called `initialIndex` or anything else if we come up with a better name.

**Comment by nstanard** [comment]
@tvler I'm a little unsure about this. Would you not simply order the slides in the order you want them to display?

Thoughts?
