### ISSUE TITLE
Add way to access lory object on element without jQuery.

### ISSUE THREAD

**Issue by tech4him1** [meandmax/lory#661]
Maybe I just can't find this, but is there any way to access the `lory` object off of an element without using jQuery?  In your jQuery example, you can do `$elements.data().lory`, and get the lory object back off of the element, but I can't see how to do this with pure JavaScript.

**Comment by justerest** [comment]
This object is created with the initialization of Lory.
```javascript
const slider = lory(element);
slider.next();
```
