### ISSUE TITLE
Infinite Stuck on Last Slide at Load

### ISSUE THREAD

**Issue by Madeck** [meandmax/lory#679]
Thank you for this simple slider!

Sometimes, when I load the page, the slider is "stuck" on the first slide. It happens about 5% of the time, but no errors are thrown. Triggering a resize or manually resizing the window seems to fix it.

Any idea what could be causing this?

**Comment by hyshka** [comment]
Same thing is happening for me, except I've also noted it happens only on larger screens. I suspect it's something to do with how I'm position the slider so will report back if I find anything out.

**Comment by hyshka** [comment]
Ok @Madeck I'm not sure if you will have the same issue but for me I needed to set `display: block;` on the `ul.slides` element and then on the individual slides (`li`) make sure I'm not setting the `font-size` or adding `white-space: normal;`.

Here's some of my code:

```
.slider-frame {
  position: relative;
  overflow: hidden;
  font-size: 0;
  line-height: 0;
  white-space: nowrap;
}

.slider-slides {
  display: block;
  padding: 0;

  > li {
    position: relative;
    display: inline-block;
    font-size: inherit;
    margin: 0;
    vertical-align: top;
    width: 100%;

    .card-text {
      white-space: normal;
    }

    img {
      vertical-align: middle;
    }
  }
}

```

**Comment by Madeck** [comment]
Yes, but I’ve decided to use another library, because I need to have text that wraps on the slides. Thanks @hyshka.

**Comment by nstanard** [comment]
@Madeck You can do anything you want with this slider. You just have to style things yourself and assign CSS properties to make it happen.

**Comment by nstanard** [comment]
Closing this because an isolated example was not provided.
