### ISSUE TITLE
No text possible on slide

### ISSUE THREAD

**Issue by kenmaclord** [meandmax/lory#687]
When trying to add a text under the picture, the .frame class force to font-size: 0 and line-height: 0. If I put a div under my image and change the font-size just inside this element, the whole slider is broken.

**Comment by nstanard** [comment]
You can provide an example in the Gitter channel and I'd be happy to help you with this.

**Comment by jacobjuul** [comment]
+1

**Comment by nstanard** [comment]
@jacobjuul 

![image](https://user-images.githubusercontent.com/4204806/32739627-13646ce0-c866-11e7-99e6-459280a8affa.png)

That's actually a carousel with only one slide. I can help you with building out slides with text if you need.
