### ISSUE TITLE
TypeError: global is undefined

### ISSUE THREAD

**Issue by majioa** [meandmax/lory#688]
in version 2.2.1 When I try to import the lory with `webpack` as follows:

    import {lory} from 'lory.js/dist/jquery.lory.js'

I'm encountering the following error `TypeError: global is undefined` with message:

    var NativeCustomEvent = global.CustomEvent;

How to fix?

**Comment by majioa** [comment]
Ok, is seems lory isn't supporting `babel-loader`, so workaround is here: https://github.com/gaearon/react-hot-loader/issues/133

**Comment by nstanard** [comment]
Did you want the jquery version of lory?

**Comment by majioa** [comment]
Not exactly, any one working
