### ISSUE TITLE
Unable to install latest version as a package.json dependency directly from github

### ISSUE THREAD

**Issue by tylik1** [meandmax/lory#690]
While it is possible to install lory.js as npm package, I can see that latest build is far behind from master branch.
If project has rare releases, would be good to be able to install it from github directly.
e.g.
`"lory.js": "git://github.com/meandmax/lory.git#master"`

Currently I have this error:

```
Could not install /var/folders/d9/3mnfwybs3ml5pr4z7n9cpwt80000gn/T/npm-11383-3d3cc438/git-cache-f6051654/5722216118c936fc3ef15d0b087fe5f4d62bde8a
npm ERR! No version provided in package.json
```

**Comment by meandmax** [comment]
@tylik1 should work now as I gave it a version in `package.json`
