### ISSUE TITLE
Flash of slide content when infinite is set to true

### ISSUE THREAD

**Issue by kyleaffolder** [meandmax/lory#698]
Came across a very weird bug that I'm having a hard time debugging and wanted to mention here in case anyone else is experiencing a similar issue or has any ideas.

Basically what I'm noticing is when I have the slider option "infinite" set to 1, when the slider transforms (loops) from the last slide back to the first, there is a very quick flash of slide content. My content is set to a dynamic width according to how the documentation suggests/gives example to. I can confirm this exists also on the [Examples](http://meandmax.github.io/lory/) page. See the "MULTIPLE SLIDES TO SCROLL" example. Notice how when the slider resets back to the first slide, there is a brief flash?

The only thing that I have been able to figure out is that I see this issue when my sliders have less than 4 slides total and infinite is set to true, there is a flash. See [this pen](https://codepen.io/anon/pen/aLJLbE). The flash occurs at the end when transitioning back to the first slide shaded red. If you uncomment the 4th slide in the HTML then the flash doesn't seem to appear.

Any ideas on why this is happening or how to resolve this? I'm running Chrome v60.0.3112.113.

**Comment by dsktschy** [comment]
Please try to set `transition-delay: 1ms` on the slides container (.js_slides) element.

**Comment by kyleaffolder** [comment]
@dsktschy Thanks so much! That resolves the issue I was experiencing! I appreciate the help and guidance.

**Comment by jveens** [comment]
I also came across this bug - of note is that I only experienced it on a retina screen. Setting the transition delay fixed it for me as well.
