### ISSUE TITLE
Feature Request: Lazy loading

### ISSUE THREAD

**Issue by kenmaclord** [meandmax/lory#703]
Hi,

This is a great slider! Would be nice if we can have a lazy-loading mode to save some bandwidth on loading, especially for mobile.

Maybe for V3.0 ?

Thanks.

**Comment by andosteinmetz** [comment]
This would be a nice feature. In the meantime, you could implement it yourself using the `before.lory.slide` event with something like:

```
<ul class="js-slider" id="my-slider">
  <li class="lory-slide js_slide">
   <img data-src="assets/some-image.jpg" src="">
  </li>
  <li class="lory-slide js_slide">
   <img data-src="assets/some-image.jpg" src="">
  </li>
</ul>

<script>
var slideContainer;

function lazyLoadSlideshowImage(currentSlide, nextSlide){
    var nextElement = slideContainer.childNodes[nextSlide];
    var image = nextElement.childNodes[0];        // or some more reliable way of getting the next image
    if( image.src === ''){
      image.src = image.dataset.src;
    }
}

document.addEventListener('DOMContentLoaded', function () {
  slideContainer = document.getElementById('my-slider');
  slideContainer.addEventListener('before.lory.slide', lazyLoadSlideshowImage);
}
</script>
```

**Comment by meandmax** [comment]
Hey @kenmaclord,

I do not see this happen in the lory core because it makes the slider more complex. Simplicity is one of the main reasons for lory and if you need something more sophisticated, there are a ton of other solutions out there offering lazy loading.

Cheers,
Max
