### ISSUE TITLE
Perctange width does not work with using a margin to space items

### ISSUE THREAD

**Issue by RicLeP** [meandmax/lory#707]
When using the following CSS the last slide will be incorrectly positioned. The same happens if I remove the margin from the last slide. Fixing the width works but that doesn’t help with responsive sites. Setting a font size above 0 on the frame does weird things too.

```
.lory__slide {
	display: inline-block;
	margin-right: 15px;
	position: relative;
	width: 100%;
}
```

**Comment by joergsteinhauer** [comment]
same here!

**Comment by Saturate** [comment]
Seems like it's not and issue and the solution has been provided, so I'll close this. If you feel this is a mistake please open it again. Thanks!
