### ISSUE TITLE
Passive Event Listeners / Scrolling Performance

### ISSUE THREAD

**Issue by yshterev** [meandmax/lory#709]
According to latest best practices setting the `passive` option on touch and wheel event listeners can improve scrolling performance, for browsers that support it. Google's Lighthouse audit tool is giving a penalty for that.

More info [on this page](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners) and also how It can be [implemented with a fallback](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection).

**Comment by johjacb** [comment]
@yshterev could you post your code solution? thanks!

**Comment by Saturate** [comment]
@johjacb this has been fixed in #715
