### ISSUE TITLE
Example code is useless

### ISSUE THREAD

**Issue by odiumediae** [meandmax/lory#721]
Have you even tried the example code in the README.md?

Well, spoiler alert: it's absolutely useless.

Why?

* setting `font-size` and `line-height` to 0 is bad practice
* not sensibly overriding these values for the children is even worse, since you're setting the slide contents to be text in the first place
* if you really want to be legacy browser compatible, why not use floats instead? They're also a little hacky, yes, but far from almost obfuscating the problem when you forget to reset properties like `font-size` and `line-height` to sensible defaults

Seriously, **lory** is really, really great, but the documentation and examples are outright awful and leave way too much to be desired. All the more for anybody else than frontend developers who know sliders well enough to probably have a few custom-build ones up their sleeves anyway which enables them to not have to fiddle around with **lory** until it finally works in the first place.

**Comment by jameskraus** [comment]
Anyone have a decent example for lory?

**Comment by kaylabranch** [comment]
@odiumediae - if you have the time, why don't you write up some better documentation/examples?

Not a fan of people whining about issues with these little open-source projects. Make a PR and contribute why don't ya.
