### ISSUE TITLE
Lory won't rewind

### ISSUE THREAD

**Issue by FutureNature** [meandmax/lory#725]
Hi folks! I tried to use the rewind feature, and read in documentation that it's not advisable to use it with infinite property. Well I tried all sort of variations even the defaults with only `rewind: true`, but with no success.

Here's my options code:
```
    var sliderOptions = {
        enableMouseEvents: true,
        slideSpeed: 1000,
        ease: 'cubic-bezier(0.7, 0.2, 0.5, 0.9)',
        rewindOnResize: false,
        rewind: true,
        rewindSpeed: 1000,
    };
```

Please tell me if there's something that i'm missing, because there're no errors in the console, and everything else regarding the slider is working just fine. Another problem that might be related is that when tried to manually reset the slider to first position using `Slider.reset();` is also not working (just resetting "active" class to the last li element.

**Comment by meandmax** [comment]
Could you please give more context, or is this not an issue anymore? Because if I take your options and paste them into one of the sliders in index.html it works just fine.

Thanks!
Cheers, Max
