### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by oneezy** [meandmax/lory#727]
When using `enableMouseEvents: true` + Google Chrome's Dev Tools "Device Toolbar" and apply a "drag" with the mouse, this bug pops up in the console. It's odd because the bug doesn't actually show up unless you've got the device toolbar opened.

![image](https://user-images.githubusercontent.com/7369575/38227185-ac2af47e-36c2-11e8-8b23-d71588cb4365.png)

**Comment by ram-you** [comment]
+1

**Comment by ram-you** [comment]
A link  to help undestand the problem:
https://developers.google.com/web/updates/2017/01/scrolling-intervention

**Comment by meandmax** [comment]
Can be closed because prevent default was removed because of other issues and because it is not needed.

Thanks for the issue.
