### ISSUE TITLE
Wrong frameWidth & slidesWidth in app webviews

### ISSUE THREAD

**Issue by Zeladin** [meandmax/lory#729]
Hey!

I just wanted to submit this issue that is kind of specific.

In webviews that are provided inside an app it happended to me that the frameWidth & slidesWidth where not correct and therefore the sliding overall would not work.

To fix this for now if have now rewritten a part of the slide function for the maxOffset.

I now have a call in there for the width of a slide and the number of slides.

For a correct sliding you just need to assign now frameWidth with the slide width and slidesWidth is frameWidth * number of slides.

I know this is a not very elegant solution but for now it was the only thing that worked for me.

Does anyone else have maybe a more elegant solution to this or is it somehow possible to make the assignment of the variables later in the script in order for the webview to fully "expand"?

**Comment by meandmax** [comment]
Hey @Zeladin,

seems that nobody else had an issue like this. I will close this issue for now, but feel free to provide a generic example with your problem and we will have a look.

Thank you
Cheers Max
