### ISSUE TITLE
TypeError: P is undefined when using https://cdnjs.cloudflare.com/ajax/libs/lory.js/2.5.1/lory.min.js

### ISSUE THREAD

**Issue by hamburger123456** [meandmax/lory#741]
by using this code.
document.addEventListener('DOMContentLoaded', function () {

    var variableWidth = document.querySelector('.slider');
    lory(variableWidth, {
        rewind: true,
        slidesToScroll: 1,
        slideSpeed: 600
    });
});
Whats wrong?

**Comment by meandmax** [comment]
check this out: https://codepen.io/anon/pen/wXRJre?editors=0010

seems to work for me, please close if it works for you now as well.

cheers Max

**Comment by hamburger123456** [comment]
works for me thx 
great job meandmax
