### ISSUE TITLE
Remove inline-styles on .destroy()

### ISSUE THREAD

**Issue by Dangoo** [meandmax/lory#83]
**Problem:**
lory.destroy() does (currently broken see https://github.com/meandmax/lory/issues/84) unregister the slider but the styles on the js_slide element remain which can cause odd optical behaviour.

**Solution:**
Maintain added styles as object and on delete match against the current inline styles of the element (to prevent foreign styles to get deleted) and remove the ones added by lory before.

**Update:**
The items cloned by lory don't get removed on .destroy() too.

**Comment by meandmax** [comment]
@Dangoo,

I removed all eventlisteners, and as far as I can see all listeners are gone. Hope this helped.

thx Max

**Comment by rjoo** [comment]
Any chance this can be reopened?

Calling destroy on a lory instance doesn't actually remove the inline styles. Unless I'm missing something. Example:

    transition-duration: 0ms; transform: translate3d(-435px, 0px, 0px); transition-timing-function: ease;

**Comment by rjoo** [comment]
After actually looking in the source, I confirmed the suspicion that nothing removes the added styles in the destroy method.

Adding a simple method and calling it when destroyed seems to take care of it.

    function untranslate () {
        const style = slideContainer && slideContainer.style;

        if (style) {
            style[prefixes.transition + 'TimingFunction'] = null;
            style[prefixes.transition + 'Duration'] = null;
            style[prefixes.transform] = null;
        }
    }

    // ...
    
    function destroy() {
        dispatchSliderEvent('before', 'destroy');

        untranslate();
        // ...
