### ISSUE TITLE
.destroy() has no effect

### ISSUE THREAD

**Issue by Dangoo** [meandmax/lory#84]
**Is:**
The .destroy() method of a lory instance has no effect => the event listeners are still active after calling.

**Should:**
The .destroy() should remove all eventListener responsible for that instance.

**Update:**
Problem are the nested addEventListener calls in `onTouchStart` which gets invoked by addEvenListener and on delete removed by removeEventListener. But the eventListeners added inside onTouchStart remain...

**Comment by meandmax** [comment]
@Dangoo,

I removed all eventlisteners, and as far as I can see all listeners are gone. Hope this helped.

thx Max
