### ISSUE TITLE
IE9 Functionality Broken

### ISSUE THREAD

**Issue by nring** [meandmax/lory#88]
I tried running the demo HTML files in IE9 and I'm getting an error:
 
```javascript
SCRIPT5007: Unable to get value of the property 'contains': object is null or undefined
lory.js, line 127 character 14
```

This obviously relates to IE9 not supporting classList 
``` if (element.classList.contains(classNameActiveSlide)) {```
but including the [suggested shim](https://github.com/eligrey/classList.js/) doesn't help either. As far as I can tell, the shim should be able to be included in the page to enable classList functionality, but it doesn't seem to be helping.

Script execution halts when this error is encountered. It looks like the lory HTML is setup correctly, but Forward/Back functionality is broken. I understand that animation is not supported for IE9.

**Comment by nring** [comment]
Correction to Original commit - the shim now works fine, no errors are reported. I was seeing errors due to something wrong on my end.

However functionality is still broken. On your demo page, none of the examples work. Though the "Showing Events" example still displays dispatched events.

**Comment by nring** [comment]
Added [pull request #89](https://github.com/meandmax/lory/pull/89). The build failed, I'm not sure if it's because of my code changes or the automated babel updates. Please advise

**Comment by meandmax** [comment]
Is the classlist topic fixed?  Than we can close this issue.

cheers Max

**Comment by meandmax** [comment]
@nring,

I close this issue with the assumption that the classlist shim works fine.

cheers Max

**Comment by nring** [comment]
Yup looks good - I wanted to wait to test the updated version before closing myself. Thanks for the quick update.

**Comment by nring** [comment]
The newest (1.6.7) no longer works in IE9 again. Locally I'm seeing a "Symbol is undefined" error on line where lory is initialized. On the demo site, I see a different error saying "Unable to get value of the property 'contains': object is null or undefined." 1.6.6 shows the same errors.

Shall I create a new issue or can you reopen this one? 

cc @levito
